### ISSUE TITLE
Module not found: Error: Can't resolve '@core/lib' in '/Users/casparsambrooksmith/Projects/trader-platform/apps/frontend/src/pages'

### ISSUE THREAD

**Issue by casparss** [nishkohli96/react-nestjs-monorepo#10]
This just started happening the last time i cloned the project when starting the frontend project with the dev command.

**Comment by casparss** [comment]
I hadn't built the package my bad.

**Comment by nishkohli96** [comment]
Yes you are correct @casparss ,I had mentioned this on the `frontend` package **README.md** . This is like a reusable package that you can customise as per your need to act as a microfrontend  or a shared collection of types, validations etc between client and server
